# Generated by Django 5.0.2 on 2024-03-02 17:10

import django.db.models.deletion
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_alter_user_subscriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='category',
            field=models.CharField(choices=[('', 'Choose Category'), ('TN', 'Tanks'), ('HL', 'Healers'), ('DD', 'Damage Dealers'), ('ME', 'Merchants'), ('GM', 'Guild Masters'), ('QG', 'Quest Givers'), ('BS', 'Blacksmiths'), ('LW', 'Tanners'), ('PM', 'Potion Makers'), ('SM', 'Spell Masters')], max_length=2, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Published at'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='text',
            field=tinymce.models.HTMLField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Heading'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='response',
            name='advert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.advert', verbose_name='Advertisement'),
        ),
        migrations.AlterField(
            model_name='response',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Published at'),
        ),
        migrations.AlterField(
            model_name='response',
            name='is_accepted',
            field=models.BooleanField(default=False, verbose_name='Accepted'),
        ),
        migrations.AlterField(
            model_name='response',
            name='text',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='response',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
    ]
